import { Router } from 'express';
import { Role, productWriteSchema, categoryWriteSchema, adminProductIdParamsSchema, adminCategoryIdParamsSchema, adminInventoryAdjustSchema, adminOrderListQuerySchema, adminDeliveryAssignmentSchema } from '@grovia/shared';
import * as controller from '../controllers/admin.controller.js';
import { authenticate } from '../middleware/authenticate.js';
import { authorize } from '../middleware/authorize.js';
import { validate } from '../middleware/validate.js';
export const adminRouter:Router=Router();
adminRouter.use(authenticate,authorize(Role.ADMIN));
adminRouter.get('/dashboard',controller.dashboard);
adminRouter.get('/products',controller.products);
adminRouter.post('/products',validate({body:productWriteSchema}),controller.createProduct);
adminRouter.patch('/products/:productId',validate({params:adminProductIdParamsSchema,body:productWriteSchema}),controller.updateProduct);
adminRouter.delete('/products/:productId',validate({params:adminProductIdParamsSchema}),controller.deleteProduct);
adminRouter.post('/products/:productId/inventory',validate({params:adminProductIdParamsSchema,body:adminInventoryAdjustSchema}),controller.inventory);
adminRouter.get('/orders',validate({query:adminOrderListQuerySchema}),controller.orders);
adminRouter.get('/categories',controller.categories);
adminRouter.post('/categories',validate({body:categoryWriteSchema}),controller.createCategory);
adminRouter.get('/delivery-partners',controller.partners);
adminRouter.post('/delivery-assignments',validate({body:adminDeliveryAssignmentSchema}),controller.assignDelivery);
adminRouter.patch('/categories/:categoryId',validate({params:adminCategoryIdParamsSchema,body:categoryWriteSchema}),controller.updateCategory);
